
spring:
  data:
    mongodb:
      uri: mongodb+srv://ayulztron12:yccwG4y6UmPJ88Lf@cluster0.fzxpfoj.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8081
  servlet:
    context-path: /journal


